language: elixir
cache:
  directories:
  - deps
  - _build/test
  - _build/dev
elixir:
  - 1.9.4
otp_release:
  - 22.2
env:
  global:
    - MIX_ENV=test
matrix:
  include:
    - otp_release: 21.3
      elixir: 1.7.0
    - otp_release: 22.2
      elixir: 1.9.4
      after_script:
        # Submit docs coverage to Inch CI
        - "mix inch.report"
        # Submit code coverage report to Coveralls
        - "mix coveralls.travis"
    - otp_release: 22.2
      elixir: 1.9.4
      env:
        - MIX_ENV=dev
      script:
        # Make sure code is formatted
        - "mix format --check-formatted"
    - otp_release: 22.2
      elixir: 1.9.4
      env:
        - MIX_ENV=dev
      script:
        # Type check
        - "mix dialyzer"
script:
  # Run all tests except pending ones
  - "mix test --exclude pending"
after_script:
# Keep it empty in order for matrix override to work
