language: elixir
cache:
  directories:
  - deps
  - _build/test
elixir:
  - 1.6.3
otp_release:
  - 20.2
env:
  global:
    - MIX_ENV=test
matrix:
  include:
    - otp_release: 20.2
      elixir: 1.6.3
      script:
        # Run all tests except pending ones
        - "mix test --exclude pending --trace"
        # Make sure code is formatted
        - "mix format --check-formatted"
        # Check type safety
        - "mix dialyzer"
    - otp_release: 19.3
      elixir: 1.5.3
script:
  # Run all tests except pending ones
  - "mix test --exclude pending --trace"
after_script:
  # Submit docs coverage to Inch CI
  - "mix inch.report"
  # Submit code coverage report to Coveralls
  - "mix coveralls.travis"
